name: Docker Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log Environment Variables
      run: env

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Log Kubernetes Cluster Info
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Describe Nodes
      run: |
        kubectl describe nodes

    - name: Build and start containers for services
      run: |
        kubectl apply -R -f ./k8s
        kubectl wait pods --all --for condition=Ready

    - name: Log Pods Status
      run: |
        kubectl get pods -o wide
        kubectl describe pods

    - name: Log Pod Logs
      run: |
        for pod in $(kubectl get pods -o=jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for $pod:";
          kubectl logs $pod;
        done

    - name: Log Events
      run: kubectl get events --sort-by='.lastTimestamp'

    - name: Port Forward to webservice
      run: kubectl port-forward service/webapp-service 8080:80 &

    - name: Log Services and Endpoints
      run: |
        kubectl get services
        kubectl get endpoints

    - name: Log Network Status
      run: |
        netstat -an
        ss -tuln

    - name: Check Node Status
      run: |
        kubectl get nodes -o wide
        kubectl describe nodes

    - name: Verify All Pods Are Ready
      run: |
        kubectl get pods --all-namespaces
        kubectl wait --for=condition=Ready pods --all --timeout=300s

    - name: List ConfigMaps and Secrets
      run: |
        kubectl get configmaps
        kubectl get secrets

    - name: Verify Deployment Status
      run: |
        kubectl get deployments -o wide
        kubectl describe deployments

    - name: Check Services and Endpoints
      run: |
        kubectl get services -o wide
        kubectl get endpoints

    - name: Display Persistent Volumes and Claims
      run: |
        kubectl get pv
        kubectl get pvc

    - name: Inspect Network Policies
      run: |
        kubectl get networkpolicies
        kubectl describe networkpolicies

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
      with:
        working-directory: ./.github/tests

    - name: Log Cypress Output
      if: always()
      run: cat cypress/screenshots/*.png || true

    - name: Log Cypress Test Results
      if: always()
      run: cat cypress/videos/*.mp4 || true

    - name: Check Logs of Failed Pods
      if: always()
      run: |
        for pod in $(kubectl get pods --field-selector=status.phase!=Running -o=jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for $pod:";
          kubectl logs $pod;
        done

    - name: Capture Resource Usage
      run: |
        kubectl top nodes
        kubectl top pods

