name: Docker Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log Environment Variables
      run: env

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Log Kubernetes Cluster Info
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Build and start containers for services
      run: |
        kubectl apply -R -f ./k8s
        kubectl wait pods --all --for condition=Ready

    - name: Log Pods Status
      run: |
        kubectl get pods -o wide
        kubectl describe pods

    - name: Port Forward to webservice
      run: kubectl port-forward service/webapp-service 8080:80 &

    - name: Log Services and Endpoints
      run: |
        kubectl get services
        kubectl get endpoints

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
      with:
        working-directory: ./.github/tests

    - name: Log Cypress Output
      if: always()
      run: cat cypress/screenshots/*.png || true
