name: Docker Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Install Metrics Server
      run: |
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        kubectl wait --namespace kube-system deployment/metrics-server --for condition=Available --timeout=90s

    - name: Build and start containers for services
      run: |
        kubectl apply -R -f ./k8s
        kubectl wait pods --all --for condition=Ready

    - name: Test PostgreSQL connectivity
      run: |
        echo "Testing PostgreSQL connectivity..."
        postgres_pod=$(kubectl get pods -l app=postgres -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$postgres_pod" ]; then
          echo "No PostgreSQL pods found. Skipping connectivity test."
        else
          kubectl exec -it $postgres_pod -- psql -U postgres -d app_production -c '\l'
        fi

    - name: Port Forward to webservice
      run: kubectl port-forward service/webapp-service 8080:80 &

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
      with:
        working-directory: ./.github/tests
